spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/D-GaLo/config-data.git
spring.cloud.config.server.git.default-label=master

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Exponer endpoints actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers,threaddump,heapdump


# Mostrar detalles de health
management.endpoint.health.show-details=always


# Instancia en eureka por hostname
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
